# -------------------------------------
# Makefile; DS2018 (v1.00)             
# (c)2018 The Open University of Japan 
# -------------------------------------

# CC  = clang
# CPP = clang++
CC  = gcc
CPP = g++
CFLAGS = -Wall -O2
LIBS = -lm

all: c1-1 c1-2 c1-3 c1-4 c1-5 c1-6 q1-1 q1-2 q1-3 q1-4 q1-5 

c1-1: c1-1.c
	$(CC) $(CFLAGS) $(LIBS) c1-1.c -o c1-1

c1-2: c1-2.c
	$(CC) $(CFLAGS) $(LIBS) c1-2.c -o c1-2

c1-3: c1-3.c
	$(CC) $(CFLAGS) $(LIBS) c1-3.c -o c1-3

c1-4: c1-4.c
	$(CC) $(CFLAGS) $(LIBS) c1-4.c -o c1-4

c1-5: c1-5.c
	$(CC) $(CFLAGS) $(LIBS) c1-5.c -o c1-5

c1-6: c1-6.c
	$(CC) $(CFLAGS) $(LIBS) c1-6.c -o c1-6

q1-1: q1-1.c
	$(CC) $(CFLAGS) $(LIBS) q1-1.c -o q1-1

q1-2: q1-2.c
	$(CC) $(CFLAGS) $(LIBS) q1-2.c -o q1-2

q1-3: q1-3.c
	$(CC) $(CFLAGS) $(LIBS) q1-3.c -o q1-3

q1-4: q1-4.c
	$(CC) $(CFLAGS) $(LIBS) q1-4.c -o q1-4

q1-5: q1-5.c
	$(CC) $(CFLAGS) $(LIBS) q1-5.c -o q1-5

clean:
	rm -rf *~  c1-1 c1-2 c1-3 c1-4 c1-5 c1-6 q1-1 q1-2 q1-3 q1-4 q1-5 

