# -------------------------------------
# Makefile; DS2018 (v1.00)             
# (c)2018 The Open University of Japan 
# -------------------------------------

# CC  = clang
# CPP = clang++
CC  = gcc
CPP = g++
CFLAGS = -Wall -O2
LIBS = -lm

all: c2-1 q2-1 q2-2 q2-3 q2-4 q2-5 q2-6 

c2-1: c2-1.c
	$(CC) $(CFLAGS) $(LIBS) c2-1.c -o c2-1

q2-1: q2-1.c
	$(CC) $(CFLAGS) $(LIBS) q2-1.c -o q2-1

q2-2: q2-2.c
	$(CC) $(CFLAGS) $(LIBS) q2-2.c -o q2-2

q2-3: q2-3.c
	$(CC) $(CFLAGS) $(LIBS) q2-3.c -o q2-3

q2-4: q2-4.c
	$(CC) $(CFLAGS) $(LIBS) q2-4.c -o q2-4

q2-5: q2-5.c
	$(CC) $(CFLAGS) $(LIBS) q2-5.c -o q2-5

q2-6: q2-6.cpp
	$(CPP) $(CFLAGS) q2-6.cpp -o q2-6

clean:
	rm -rf *~  c2-1 q2-1 q2-2 q2-3 q2-4 q2-5 q2-6 

