# -------------------------------------
# Makefile; DS2018 (v1.00)             
# (c)2018 The Open University of Japan 
# -------------------------------------

# CC  = clang
# CPP = clang++
CC  = gcc
CPP = g++
CFLAGS = -Wall -O2
LIBS = -lm

all: c4-1 c4-2 c4-3 q4-1 q4-2 q4-3 q4-4 q4-5 q4-6 

c4-1: c4-1.c
	$(CC) $(CFLAGS) $(LIBS) c4-1.c -o c4-1

c4-2: c4-2.c
	$(CC) $(CFLAGS) $(LIBS) c4-2.c -o c4-2

c4-3: c4-3.c
	$(CC) $(CFLAGS) $(LIBS) c4-3.c -o c4-3

q4-1: q4-1.c
	$(CC) $(CFLAGS) $(LIBS) q4-1.c -o q4-1

q4-2: q4-2.c
	$(CC) $(CFLAGS) $(LIBS) q4-2.c -o q4-2

q4-3: q4-3.c
	$(CC) $(CFLAGS) $(LIBS) q4-3.c -o q4-3

q4-4: q4-4.c
	$(CC) $(CFLAGS) $(LIBS) q4-4.c -o q4-4

q4-5: q4-5.c
	$(CC) $(CFLAGS) $(LIBS) q4-5.c -o q4-5

q4-6: q4-6.cpp
	$(CPP) $(CFLAGS) q4-6.cpp -o q4-6

clean:
	rm -rf *~  c4-1 c4-2 c4-3 q4-1 q4-2 q4-3 q4-4 q4-5 q4-6 

