# -------------------------------------
# Makefile; DS2018 (v1.00)             
# (c)2018 The Open University of Japan 
# -------------------------------------

# CC  = clang
# CPP = clang++
CC  = gcc
CPP = g++
CFLAGS = -Wall -O2
LIBS = -lm

all: c6-1 c6-2 c6-3 q6-1 q6-2 q6-3 

c6-1: c6-1.c
	$(CC) $(CFLAGS) $(LIBS) c6-1.c -o c6-1

c6-2: c6-2.c
	$(CC) $(CFLAGS) $(LIBS) c6-2.c -o c6-2

c6-3: c6-3.c
	$(CC) $(CFLAGS) $(LIBS) c6-3.c -o c6-3

q6-1: q6-1.c
	$(CC) $(CFLAGS) $(LIBS) q6-1.c -o q6-1

q6-2: q6-2.c
	$(CC) $(CFLAGS) $(LIBS) q6-2.c -o q6-2

q6-3: q6-3.c
	$(CC) $(CFLAGS) $(LIBS) q6-3.c -o q6-3

clean:
	rm -rf *~  c6-1 c6-2 c6-3 q6-1 q6-2 q6-3 

