# -------------------------------------
# Makefile; DS2018 (v1.00)             
# (c)2018 The Open University of Japan 
# -------------------------------------

# CC  = clang
# CPP = clang++
CC  = gcc
CPP = g++
CFLAGS = -Wall -O2
LIBS = -lm

all: c13-1 c13-2 c13-3 c13-4 q13-1 q13-2 q13-3 q13-4 q13-5 

c13-1: c13-1.c
	$(CC) $(CFLAGS) $(LIBS) c13-1.c -o c13-1

c13-2: c13-2.c
	$(CC) $(CFLAGS) $(LIBS) c13-2.c -o c13-2

c13-3: c13-3.c
	$(CC) $(CFLAGS) $(LIBS) c13-3.c -o c13-3

c13-4: c13-4.c
	$(CC) $(CFLAGS) $(LIBS) c13-4.c -o c13-4

q13-1: q13-1.c
	$(CC) $(CFLAGS) $(LIBS) q13-1.c -o q13-1

q13-2: q13-2.c
	$(CC) $(CFLAGS) $(LIBS) q13-2.c -o q13-2

q13-3: q13-3.c
	$(CC) $(CFLAGS) $(LIBS) q13-3.c -o q13-3

q13-4: q13-4.c
	$(CC) $(CFLAGS) $(LIBS) q13-4.c -o q13-4

q13-5: q13-5.c
	$(CC) $(CFLAGS) $(LIBS) q13-5.c -o q13-5

clean:
	rm -rf *~  c13-1 c13-2 c13-3 c13-4 q13-1 q13-2 q13-3 q13-4 q13-5 

