# -------------------------------------
# Makefile; DS2018 (v1.00)             
# (c)2018 The Open University of Japan 
# -------------------------------------

# CC  = clang
# CPP = clang++
CC  = gcc
CPP = g++
CFLAGS = -Wall -O2
LIBS = -lm

all: c7-1 c7-2 c7-3 q7-1 q7-2 q7-3 

c7-1: c7-1.c
	$(CC) $(CFLAGS) $(LIBS) c7-1.c -o c7-1

c7-2: c7-2.c
	$(CC) $(CFLAGS) $(LIBS) c7-2.c -o c7-2

c7-3: c7-3.c
	$(CC) $(CFLAGS) $(LIBS) c7-3.c -o c7-3

q7-1: q7-1.c
	$(CC) $(CFLAGS) $(LIBS) q7-1.c -o q7-1

q7-2: q7-2.c
	$(CC) $(CFLAGS) $(LIBS) q7-2.c -o q7-2

q7-3: q7-3.c
	$(CC) $(CFLAGS) $(LIBS) q7-3.c -o q7-3

clean:
	rm -rf *~  c7-1 c7-2 c7-3 q7-1 q7-2 q7-3 

