# -------------------------------------
# Makefile; DS2018 (v1.00)             
# (c)2018 The Open University of Japan 
# -------------------------------------

# CC  = clang
# CPP = clang++
CC  = gcc
CPP = g++
CFLAGS = -Wall -O2
LIBS = -lm

all: c14-1 c14-2 q14-1 q14-2 q14-3 q14-4 

c14-1: c14-1.c
	$(CC) $(CFLAGS) $(LIBS) c14-1.c -o c14-1

c14-2: c14-2.c
	$(CC) $(CFLAGS) $(LIBS) c14-2.c -o c14-2

q14-1: q14-1.c
	$(CC) $(CFLAGS) $(LIBS) q14-1.c -o q14-1

q14-2: q14-2.c
	$(CC) $(CFLAGS) $(LIBS) q14-2.c -o q14-2

q14-3: q14-3.c
	$(CC) $(CFLAGS) $(LIBS) q14-3.c -o q14-3

q14-4: q14-4.c
	$(CC) $(CFLAGS) $(LIBS) q14-4.c -o q14-4

clean:
	rm -rf *~  c14-1 c14-2 q14-1 q14-2 q14-3 q14-4 

