# -------------------------------------
# Makefile; DS2018 (v1.00)             
# (c)2018 The Open University of Japan 
# -------------------------------------

# CC  = clang
# CPP = clang++
CC  = gcc
CPP = g++
CFLAGS = -Wall -O2
LIBS = -lm

all: c10-1 c10-2 q10-1 q10-2 q10-3 q10-4 q10-5 

c10-1: c10-1.c
	$(CC) $(CFLAGS) $(LIBS) c10-1.c -o c10-1

c10-2: c10-2.c
	$(CC) $(CFLAGS) $(LIBS) c10-2.c -o c10-2

q10-1: q10-1.c
	$(CC) $(CFLAGS) $(LIBS) q10-1.c -o q10-1

q10-2: q10-2.c
	$(CC) $(CFLAGS) $(LIBS) q10-2.c -o q10-2

q10-3: q10-3.c
	$(CC) $(CFLAGS) $(LIBS) q10-3.c -o q10-3

q10-4: q10-4.c
	$(CC) $(CFLAGS) $(LIBS) q10-4.c -o q10-4

q10-5: q10-5.c
	$(CC) $(CFLAGS) $(LIBS) q10-5.c -o q10-5

clean:
	rm -rf *~  c10-1 c10-2 q10-1 q10-2 q10-3 q10-4 q10-5 

