# -------------------------------------
# Makefile; DS2018 (v1.00)             
# (c)2018 The Open University of Japan 
# -------------------------------------

# CC  = clang
# CPP = clang++
CC  = gcc
CPP = g++
CFLAGS = -Wall -O2
LIBS = -lm

all: c9-1 q9-1 q9-2 

c9-1: c9-1.c
	$(CC) $(CFLAGS) $(LIBS) c9-1.c -o c9-1

q9-1: q9-1.c
	$(CC) $(CFLAGS) $(LIBS) q9-1.c -o q9-1

q9-2: q9-2.c
	$(CC) $(CFLAGS) $(LIBS) q9-2.c -o q9-2

clean:
	rm -rf *~  c9-1 q9-1 q9-2 

