# -------------------------------------
# Makefile; DS2018 (v1.00)             
# (c)2018 The Open University of Japan 
# -------------------------------------

# CC  = clang
# CPP = clang++
CC  = gcc
CPP = g++
CFLAGS = -Wall -O2
LIBS = -lm

all: c8-1 c8-2 c8-3 c8-4 q8-1 q8-2 q8-3 q8-4 

c8-1: c8-1.c
	$(CC) $(CFLAGS) $(LIBS) c8-1.c -o c8-1

c8-2: c8-2.c
	$(CC) $(CFLAGS) $(LIBS) c8-2.c -o c8-2

c8-3: c8-3.c
	$(CC) $(CFLAGS) $(LIBS) c8-3.c -o c8-3

c8-4: c8-4.c
	$(CC) $(CFLAGS) $(LIBS) c8-4.c -o c8-4

q8-1: q8-1.c
	$(CC) $(CFLAGS) $(LIBS) q8-1.c -o q8-1

q8-2: q8-2.c
	$(CC) $(CFLAGS) $(LIBS) q8-2.c -o q8-2

q8-3: q8-3.c
	$(CC) $(CFLAGS) $(LIBS) q8-3.c -o q8-3

q8-4: q8-4.c
	$(CC) $(CFLAGS) $(LIBS) q8-4.c -o q8-4

clean:
	rm -rf *~  c8-1 c8-2 c8-3 c8-4 q8-1 q8-2 q8-3 q8-4 

