# -------------------------------------
# Makefile; DS2018 (v1.00)             
# (c)2018 The Open University of Japan 
# -------------------------------------

# CC  = clang
# CPP = clang++
CC  = gcc
CPP = g++
CFLAGS = -Wall -O2
LIBS = -lm

all: c12-1 c12-2 c12-3 c12-4 c12-5 q12-1 q12-2 q12-3 

c12-1: c12-1.c
	$(CC) $(CFLAGS) $(LIBS) c12-1.c -o c12-1

c12-2: c12-2.c
	$(CC) $(CFLAGS) $(LIBS) c12-2.c -o c12-2

c12-3: c12-3.c
	$(CC) $(CFLAGS) $(LIBS) c12-3.c -o c12-3

c12-4: c12-4.c
	$(CC) $(CFLAGS) $(LIBS) c12-4.c -o c12-4

c12-5: c12-5.c
	$(CC) $(CFLAGS) $(LIBS) c12-5.c -o c12-5

q12-1: q12-1.c
	$(CC) $(CFLAGS) $(LIBS) q12-1.c -o q12-1

q12-2: q12-2.c
	$(CC) $(CFLAGS) $(LIBS) q12-2.c -o q12-2

q12-3: q12-3.c
	$(CC) $(CFLAGS) $(LIBS) q12-3.c -o q12-3

clean:
	rm -rf *~  c12-1 c12-2 c12-3 c12-4 c12-5 q12-1 q12-2 q12-3 

