# -------------------------------------
# Makefile; DS2018 (v1.00)             
# (c)2018 The Open University of Japan 
# -------------------------------------

# CC  = clang
# CPP = clang++
CC  = gcc
CPP = g++
CFLAGS = -Wall -O2
LIBS = -lm

all: q15-1 q15-2 q15-3 

q15-1: q15-1.c
	$(CC) $(CFLAGS) $(LIBS) q15-1.c -o q15-1

q15-2: q15-2.c
	$(CC) $(CFLAGS) $(LIBS) q15-2.c -o q15-2

q15-3: q15-3.c
	$(CC) $(CFLAGS) $(LIBS) q15-3.c -o q15-3

clean:
	rm -rf *~  q15-1 q15-2 q15-3 

