# -------------------------------------
# Makefile; DS2018 (v1.00)             
# (c)2018 The Open University of Japan 
# -------------------------------------

# CC  = clang
# CPP = clang++
CC  = gcc
CPP = g++
CFLAGS = -Wall -O2
LIBS = -lm

all: c11-1 c11-2 c11-3 c11-4 c11-5 c11-6 c11-7 c11-8 q11-1 q11-2 q11-3 q11-4 

c11-1: c11-1.c
	$(CC) $(CFLAGS) $(LIBS) c11-1.c -o c11-1

c11-2: c11-2.c
	$(CC) $(CFLAGS) $(LIBS) c11-2.c -o c11-2

c11-3: c11-3.c
	$(CC) $(CFLAGS) $(LIBS) c11-3.c -o c11-3

c11-4: c11-4.c
	$(CC) $(CFLAGS) $(LIBS) c11-4.c -o c11-4

c11-5: c11-5.c
	$(CC) $(CFLAGS) $(LIBS) c11-5.c -o c11-5

c11-6: c11-6.c
	$(CC) $(CFLAGS) $(LIBS) c11-6.c -o c11-6

c11-7: c11-7.c
	$(CC) $(CFLAGS) $(LIBS) c11-7.c -o c11-7

c11-8: c11-8.c
	$(CC) $(CFLAGS) $(LIBS) c11-8.c -o c11-8

q11-1: q11-1.c
	$(CC) $(CFLAGS) $(LIBS) q11-1.c -o q11-1

q11-2: q11-2.c
	$(CC) $(CFLAGS) $(LIBS) q11-2.c -o q11-2

q11-3: q11-3.c
	$(CC) $(CFLAGS) $(LIBS) q11-3.c -o q11-3

q11-4: q11-4.c
	$(CC) $(CFLAGS) $(LIBS) q11-4.c -o q11-4

clean:
	rm -rf *~  c11-1 c11-2 c11-3 c11-4 c11-5 c11-6 c11-7 c11-8 q11-1 q11-2 q11-3 q11-4 

